(function(){
const KEY='laSostaDemoV1';
const menu=window.LA_SOSTA_MENUS||{};
const cats={pizze:'Pizze',speciali:'Speciali & bianche',primi:'Primi',secondi:'Secondi',hamburger:'Hamburger',contorni:'Contorni',dolci:'Dolci'};
let state=JSON.parse(localStorage.getItem(KEY)||'null')||{
 user:null,
 reservations:[
  {id:'LS-1001',name:'Marco Rossi',phone:'333 1234567',date:'2026-10-10',time:'20:30',people:12,note:'Compleanno',status:'Confermata',preorder:{pizze:7,primi:5,secondi:3,contorni:4,note:'2 persone vegetariane'}}
 ],
 preorderStatus:'Ricevuto'
};
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function esc(s){return String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function app(){const root=document.getElementById('demo-app'); if(!state.user)return login(root); state.user==='admin'?admin(root):client(root)}
function login(root){
root.innerHTML='<div class="demo-login"><div class="demo-head"><div><p class="eyebrow">LA SOSTA · PROTOTIPO</p><h1>Area demo</h1><p class="demo-muted">Versione di prova: nessun dato viene inviato a un server.</p></div></div><div class="demo-panel"><h2>Scegli un profilo</h2><p class="demo-muted">Usa i due ruoli per mostrarne il funzionamento al ristorante.</p><div class="demo-user-buttons"><button onclick="demoLogin(\'client\')">👤 Cliente demo<br><small>Marco Rossi</small></button><button onclick="demoLogin(\'admin\')">🍽️ Ristorante<br><small>La Sosta · Admin</small></button></div></div></div>'}
window.demoLogin=r=>{state.user=r;save();app()}
window.demoLogout=()=>{state.user=null;save();app()}
function nav(active){return '<div class="demo-tabs"><button class="'+(active==='client'?'active':'')+'" onclick="demoView(\'client\')">Area cliente</button><button class="'+(active==='admin'?'active':'')+'" onclick="demoView(\'admin\')">Area ristorante</button><button onclick="demoLogout()">Esci</button></div>'}
window.demoView=r=>{state.user=r;app()}
function client(root){
const mine=state.reservations.filter(r=>r.name==='Marco Rossi');
root.innerHTML='<div class="demo-shell"><div class="demo-head"><div><p class="eyebrow">AREA CLIENTE · DEMO</p><h1>Ciao, Marco.</h1><p class="demo-muted">Gestisci le tue prenotazioni e prepara il pre-ordine per i gruppi.</p></div><div class="demo-badge">LOCALSTORAGE</div></div>'+nav('client')+'<div class="demo-grid"><section class="demo-panel"><h2>Nuova prenotazione</h2><div class="demo-form"><label>Nome<input id="rname" value="Marco Rossi"></label><label>Telefono<input id="rphone" value="333 1234567"></label><label>Data<input id="rdate" type="date" value="2026-10-17"></label><label>Ora<input id="rtime" type="time" value="20:30"></label><label>Persone<input id="rpeople" type="number" min="1" value="4"></label><label class="full">Note<textarea id="rnote" placeholder="Allergie, compleanno, richieste..."></textarea></label></div><div class="demo-actions"><button class="btn" onclick="newReservation()">Invia richiesta</button></div></section><section class="demo-panel"><h2>Le mie prenotazioni</h2><div class="demo-list">'+(mine.length?mine.map(resCard).join(''):'<div class="empty">Nessuna prenotazione.</div>')+'</div></section></div></div>'}
function resCard(r){
const hasGroup=r.people>=8; return '<div class="demo-row"><div class="demo-row-top"><div><b>'+esc(r.date)+' · '+esc(r.time)+'</b><div class="demo-muted">'+r.people+' persone · '+esc(r.note||'Nessuna nota')+'</div></div><span class="demo-status ok">'+esc(r.status)+'</span></div>'+(hasGroup?'<div class="demo-actions"><button class="btn" onclick="openPreorder(\''+r.id+'\')">Preparare il pre-ordine</button></div>':'')}
window.newReservation=()=>{const r={id:'LS-'+Date.now().toString().slice(-6),name:document.getElementById('rname').value,phone:document.getElementById('rphone').value,date:document.getElementById('rdate').value,time:document.getElementById('rtime').value,people:+document.getElementById('rpeople').value,note:document.getElementById('rnote').value,status:'In attesa'};state.reservations.unshift(r);save();app()}
window.openPreorder=id=>{const r=state.reservations.find(x=>x.id===id); if(!r)return; const items=Object.keys(cats).flatMap(c=>(menu[c]||[]).map(x=>({cat:c,name:x[0],desc:x[1],price:x[2],qty:0}))); root=document.getElementById('demo-app');root.innerHTML='<div class="demo-shell"><div class="demo-head"><div><p class="eyebrow">PRE-ORDINE · GRUPPO</p><h1>'+r.people+' persone.</h1><p class="demo-muted">Prenotazione '+esc(r.date)+' · '+esc(r.time)+' · '+esc(r.id)+'</p></div></div>'+nav('client')+'<div class="demo-panel"><div class="alert"><b>Importante:</b> questo è un pre-ordine. La comanda definitiva viene confermata al vostro arrivo.</div><div id="preorder-list">'+Object.entries(cats).map(([c,label])=>'<div><h3>'+label+'</h3>'+items.filter(x=>x.cat===c).map(x=>'<div class="qty-row"><div><b>'+esc(x.name)+'</b><div class="demo-muted">'+esc(x.desc)+'</div></div><div class="qty"><button onclick="changeQty(this,-1)">−</button><b data-name="'+esc(x.name)+'" data-cat="'+c+'" data-price="'+x.price+'">0</b><button onclick="changeQty(this,1)">+</button></div></div>').join('')+'</div>').join('')}<div class="demo-form" style="margin-top:25px"><label class="full">Osservazioni<textarea id="ponote" placeholder="Ex.: 2 vegetariani, 1 persona senza frutti di mare..."></textarea></label></div><div class="demo-actions"><button class="btn" onclick="sendPreorder(\''+r.id+'\')">Invia pre-ordine</button><button class="btn btn-ghost" onclick="app()">Annulla</button></div></div></div>'}
window.changeQty=(btn,delta)=>{const b=btn.parentElement.querySelector('b');let n=Math.max(0,+b.textContent+delta);b.textContent=n}
window.sendPreorder=id=>{const r=state.reservations.find(x=>x.id===id);const out={};document.querySelectorAll('#preorder-list .qty b[data-name]').forEach(b=>{const q=+b.textContent;if(q)out[b.dataset.name]={qty:q,cat:b.dataset.cat,price:b.dataset.price}});r.preorder={items:out,note:document.getElementById('ponote').value};r.preorderStatus='Ricevuto';save();app()}
function admin(root){
const all=state.reservations, pending=all.filter(r=>r.preorderStatus==='Ricevuto').length, groups=all.filter(r=>r.people>=8).length;
root.innerHTML='<div class="demo-shell"><div class="demo-head"><div><p class="eyebrow">AREA RISTORANTE · DEMO</p><h1>Buonasera, La Sosta.</h1><p class="demo-muted">Dashboard di prova per prenotazioni e pre-ordini.</p></div><div class="demo-badge">ADMIN</div></div>'+nav('admin')+'<div class="demo-kpis"><div class="demo-kpi"><b>'+all.length+'</b><span>Prenotazioni</span></div><div class="demo-kpi"><b>'+groups+'</b><span>Gruppi</span></div><div class="demo-kpi"><b>'+pending+'</b><span>Pre-ordini nuovi</span></div><div class="demo-kpi"><b>'+all.filter(r=>r.status==='Confermata').length+'</b><span>Confermate</span></div></div><section class="demo-panel"><h2>Agenda & pre-ordini</h2><div class="demo-list">'+(all.length?all.map(adminCard).join(''):'<div class="empty">Nessun dato.</div>')+'</div></section></div>'}
function adminCard(r){
let items=r.preorder&&r.preorder.items?Object.entries(r.preorder.items).map(([n,x])=>x.qty+'× '+n).join(' · '):'Nessun pre-ordine';
return '<div class="demo-row"><div class="demo-row-top"><div><h3>'+esc(r.name)+'</h3><b>'+esc(r.date)+' · '+esc(r.time)+' · '+r.people+' persone</b><div class="demo-muted">'+esc(r.phone)+' · '+esc(r.note||'')+'</div></div><span class="demo-status '+(r.preorderStatus?'pending':'')+'">'+esc(r.preorderStatus||r.status)+'</span></div><p class="demo-muted" style="margin:12px 0"><b>Pre-ordine:</b> '+esc(items)+'</p>'+(r.preorder&&r.preorder.note?'<p class="demo-muted"><b>Note cucina:</b> '+esc(r.preorder.note)+'</p>':'')+'<div class="demo-actions">'+(r.preorder?'<button class="btn" onclick="confirmPreorder(\''+r.id+'\')">Conferma ricezione</button>':'')+'<button class="btn btn-ghost" onclick="confirmReservation(\''+r.id+'\')">Conferma prenotazione</button></div></div>'}
window.confirmPreorder=id=>{const r=state.reservations.find(x=>x.id===id);r.preorderStatus='Confermato';save();app()}
window.confirmReservation=id=>{const r=state.reservations.find(x=>x.id===id);r.status='Confermata';save();app()}
app();
})();